name: cppcheck-action-test
on:
  pull_request:

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          output_file: ./cppcheck_report.txt

      - name: extract branch name
        run: |
          BRANCH_NAME=`echo ${GITHUB_REF##*/}` >> $GITHUB_ENV

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
