name: cppcheck-action-test
on:
  push:

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check_library: disable
          skip_preprocessor: disable
          enable: all #performance,portability,warning
          inconclusive: disable
          inline_suppression: disable
          force_language: c++
          force: enable
          max_ctu_depth: 12
          platform: disable
          #std: c11
          output_file: ./CppCheckReport.txt
          other_options: e2e-examples/gcs/benchmark --verbose --std=c11

      - name: publish report
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master'
